name: reviewdog

on: [pull_request]

jobs:
  black-format-check:
    name: Black Format Check
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.11
      - name: Install black
        run: python -m pip install black
      - name: Run black with reviewdog
        uses: reviewdog/action-black@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
